import os
import requests
import tweepy
from dotenv import load_dotenv
from mcp.server.fastmcp import FastMCP, Context
from typing import Optional
import google.generativeai as genai


mcp = FastMCP("Twitter MCP Tool", dependencies=["tweepy","google-genai"])

load_dotenv()
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

async def get_twitter_client() -> tweepy.Client:
    api_key = os.getenv('X_api_key')
    api_secret = os.getenv('X_api_key_sec')
    access_token = os.getenv('X_access_token')
    access_token_secret = os.getenv('X_access_token_sec')
    bearer_token = os.getenv('X_bearer_token')

    return tweepy.Client(
        bearer_token=bearer_token,
        consumer_key=api_key,
        consumer_secret=api_secret,
        access_token=access_token,
        access_token_secret=access_token_secret,
        wait_on_rate_limit=True
    )


@mcp.tool()
def tweet_posting(text: str) -> str:
    """ Text should be less than 280 characters as input """
    try:
        # Load credentials
        api_key = os.getenv('X_api_key')
        api_secret = os.getenv('X_api_key_sec')
        access_token = os.getenv('X_access_token')
        access_token_secret = os.getenv('X_access_token_sec')
        bearer_token = os.getenv('X_bearer_token')

        client_v2 = tweepy.Client(
            bearer_token=bearer_token,
            consumer_key=api_key,
            consumer_secret=api_secret,
            access_token=access_token,
            access_token_secret=access_token_secret,
            wait_on_rate_limit=True
        )
        
        response = client_v2.create_tweet(text=text)
        return f"✅ Tweet posted: {response.data['id']}"


    except tweepy.TweepyException as e:
        return f"❌ Twitter error: {e}"

    except Exception as e:
        return f"❌ Unexpected error: {e}"
    
@mcp.tool()
def tweet_posting_with_llm(text: Optional[str] = None, topic: Optional[str] = None) -> str:
    """
        Posts a tweet generated by Gemini or from user input.
        Params:
            text (str): Tweet text (optional if topic is given)
            topic (str): Topic to generate tweet with Gemini (optional if text is given)
    """
    try:
        # Load credentials
        api_key = os.getenv('X_api_key')
        api_secret = os.getenv('X_api_key_sec')
        access_token = os.getenv('X_access_token')
        access_token_secret = os.getenv('X_access_token_sec')
        bearer_token = os.getenv('X_bearer_token')

        if not text:
            return "❌ No tweet text provided or generated."
        if len(text) > 280:
            text = text[:277] + "..."

        auth_v1 = tweepy.OAuth1UserHandler(api_key, api_secret)
        auth_v1.set_access_token(access_token, access_token_secret)
        client_v1 = tweepy.API(auth_v1, wait_on_rate_limit=True)

        client_v2 = tweepy.Client(
            bearer_token=bearer_token,
            consumer_key=api_key,
            consumer_secret=api_secret,
            access_token=access_token,
            access_token_secret=access_token_secret,
            wait_on_rate_limit=True
        )

        if not text and topic:
            gemini_model = genai.GenerativeModel("gemini-1.5-flash")
            prompt = f"Write a tweet about '{topic}', under 280 characters, clear and engaging."
            response = gemini_model.generate_content(prompt)
            text = response.text.strip()

        media_ids = None
        response = client_v2.create_tweet(text=text, media_ids=media_ids)
        tweet_id = response.data['id']
        return f"✅ Tweet posted: https://twitter.com/user/status/{tweet_id}"


    except tweepy.TweepyException as e:
        return f"❌ Twitter error: {e}"

    except Exception as e:
        return f"❌ Unexpected error: {e}"
   

@mcp.tool()
def track_username_history(username: str) -> str:
    """
    Track the username change history for a Twitter user using the memory.

    Parameters:
        username (str): The current Twitter user name (handle) of the user, without the '@' symbol.
                          For example, use 'OSINT_Ukraine' for '@OSINT_Ukraine'.
                          Case-insensitive and must be a valid Twitter handle.

    Returns:
        A formatted string containing the username change history, including user ID and timestamps.
        If no history is found or an error occurs, returns an error message.
    """
    
    # Fetch data from memory.lol API
    try:
        response = requests.get(f"https://api.memory.lol/v1/tw/{username}")
        response.raise_for_status()
        data = response.json()
    except requests.HTTPError as e:
        return f"Error: Failed to fetch data for {username} (status {e.response.status_code})"
    except requests.RequestException:
        return f"Error: Network issue while fetching data for {username}"

    if not data.get("accounts"):
        return f"No username change history found for {username}"

    # Format username change history
    formatted_history = []
    for account in data["accounts"]:
        user_id = account["id_str"]
        usernames = account["screen_names"]
        history = "\n".join(
            f"- {name} ({' to '.join(dates) if isinstance(dates, list) else dates})"
            for name, dates in usernames.items()
        )
        formatted_history.append(f"User ID {user_id}:\n{history}")
    
    return f"Username change history for {username}:\n\n" + "\n\n".join(formatted_history)


def convert_tweets_to_markdown(tweets: Optional[tweepy.Response]) -> str:
    if not tweets or not tweets.data:
        return "No tweets found."

    output = []
    for tweet in tweets.data:
        output.append(f"- 🕒 {tweet.created_at}:\n  {tweet.text}\n")
    return "\n".join(output)

# Main MCP tool
@mcp.tool()
async def fetch_recent_tweets(username: str, count: int = 10) -> str:
    """Fetch recent tweets from a user's timeline."""
    try:
        client = await get_twitter_client()
        username = username.lstrip('@')

        # ❌ Removed `await` - these are synchronous calls
        user_response = client.get_user(username=username)
        if not user_response or not user_response.data:
            return f"❌ Could not find user: @{username}"

        user_id = user_response.data.id
        tweets = client.get_users_tweets(
            id=user_id,
            max_results=count,
            tweet_fields=["created_at", "text"]
        )

        return convert_tweets_to_markdown(tweets)
    except Exception as e:
        return f"⚠️ Failed to get tweets for @{username}: {str(e)}"

if __name__ == "__main__":
    mcp.run(transport="sse")